### ISSUE TITLE
提示缺少 libbz2.so.1.1()(64bit)

### ISSUE THREAD

**Issue by thutian** [sainnhe/wechat-universal-bwrap-rpm#1]
在fedora40下安装提示缺少 libbz2.so.1.0()(64bit)

**Comment by sainnhe** [comment]
复现不了，我就是在f40上打包的，之前还用copr提供的ci打包过，没出现这个问题。麻烦附上复现步骤

**Comment by sainnhe** [comment]
由于没有回复，所以先关了

**Comment by zhufengning** [comment]
执行`sudo cp /usr/lib64/libbz2.so.1 /usr/lib64/libbz2.so.1.0`后，用rpm带上--nodeps参数安装即可
