### ISSUE TITLE
启动脚本问题

### ISSUE THREAD

**Issue by zhufengning** [sainnhe/wechat-universal-bwrap-rpm#2]
/usr/bin/wechat-universal中的
```
    --symlink usr/lib /lib
    --symlink usr/lib /lib64
```
应把第二行改为`--symlink usr/lib64 /lib64`，否则会因找不到interpreter而报`bwrap: execvp bash: No such file or directory`

**Comment by sainnhe** [comment]
感谢提醒，已经修好了 https://github.com/sainnhe/wechat-universal-bwrap-rpm/commit/c4150973cdf2367584f336fc37e7c3d03ee94999

另外这个仓库我打算归档了，因为我现在没有在用asahi linux 了。欢迎 fork
